version: 2
jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - run:
          name: Install required packages
          command: yes | pacman -Sy cmake z openssl git
      - checkout
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Prepare environment
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: make -j4
